export default snowWeather = [ 
        {
            key: 0,
            anum: "134",
            acronymn: "CN",
            kind: 'Snow Formations ❄️',
            title: 'Cornice',
            desc: 'Overhanging build-up	of snow, sometimes looking like a wave, hanging over a ridge.',
            backgroundColor: "#DDEBF7",
        },
        {
            key: 1,
            anum: "135",
            acronymn: "AVA",
            kind: 'Snow Formations ❄️',
            title: 'Avalanche',
            desc: 'A rapid slide of snow down a hillside or mountain; Snow flow dangerous and deadly.',
            backgroundColor: "#DDEBF7",
        },
        {
            key: 2,
            anum: "136",
            acronymn: "SB",
            kind: 'Snow Formations ❄️',
            title: 'Snow Bridge',
            desc: 'A span of snow arcing over a void, such as a crevasse or gap, but destined to collapse.',
            backgroundColor: "#DDEBF7",
        },
        {
            key: 3,
            anum: "137",
            acronymn: "DR",
            kind: 'Snow Formations ❄️',
            title: 'Snowdrift',
            desc: 'Wind and snowfall combine in an artful manner to form a wide variety of snow shapes.',
            backgroundColor: "#DDEBF7",
        },
        {
            key: 4,
            anum: "138",
            acronymn: "FD",
            kind: 'Snow Formations ❄️',
            title: 'Finger Drift',
            desc: 'A narrow drift of snow, up to 36 inches wide; Several close by resemble a hand.',
            backgroundColor: "#DDEBF7",
        },
        {
            key: 5,
            anum: "139",
            acronymn: "PD",
            kind: 'Snow Formations ❄️',
            title: 'Pillow Drift',
            desc: 'A drift of snow often 10-15 feet long and 1-3 feet wide; No idea why its called "pillow".',
            backgroundColor: "#DDEBF7",
        },
        {
            key: 6,
            anum: "140",
            acronymn: "RP",
            kind: 'Snow Formations ❄️',
            title: 'Ripple Marks',
            desc: 'Corrugated surface of snow created by wind; Looks like the ripples on a sandy surface.',
            backgroundColor: "#DDEBF7",
        },
        {
            key: 7,
            anum: "141",
            acronymn: "CAV",
            kind: 'Snow Formations ❄️',
            title: 'Snow Cave',
            desc: 'A shelter carved into snow bank by animals or people to protect from wind and cold.',
            backgroundColor: "#DDEBF7",
        },
        {
            key: 8,
            anum: "142",
            acronymn: "KIK",
            kind: 'Snow Formations ❄️',
            title: 'Kicker',
            desc: 'A curved ramp that sends the rider up into the air, for launcing big air, tricks, big falls.',
            backgroundColor: "#DDEBF7",
        },
        {
            key: 9,
            anum: "143",
            acronymn: "PIP",
            kind: 'Snow Formations ❄️',
            title: 'Half Pipe',
            desc: 'A terrain feature shaped like a half tube of snow, with a down-hill pitch, for tricks.',
            backgroundColor: "#DDEBF7",
        },
        {
            key: 10,
            anum: "144",
            acronymn: "MOG",
            kind: 'Snow Formations ❄️',
            title: 'Mogul',
            desc: 'Series of snow bumps formed by skiers who push snow into oval-rounded shapes.',
            backgroundColor: "#DDEBF7",
        },
        {
            key: 11,
            anum: "145",
            acronymn: "PIL",
            kind: 'Snow Formations ❄️',
            title: 'Pillow',
            desc: 'A soft pile of snow atop a rock or raised feature; Really fun to drop onto from above.',
            backgroundColor: "#DDEBF7",
        },
        {
            key: 12,
            anum: "146",
            acronymn: "MAN",
            kind: 'Snow Formations ❄️',
            title: 'Snowman',
            desc: 'Stacked structure of 3 snowballs, w/ smaller ones on top, highest ball with face features.',
            backgroundColor: "#DDEBF7",
        },
        {
            key: 13,
            anum: "147",
            acronymn: "WOM",
            kind: 'Snow Formations ❄️',
            title: 'Snowwoman',
            desc: 'Much like Snowman, but containing artful and gender-specific features and fashions.',
            backgroundColor: "#DDEBF7",
        },
        {
            key: 14,
            anum: "148",
            acronymn: "SS",
            kind: 'Snow Weather ❄️',
            title: 'Snowstorm',
            desc: 'Winter storm with some amounts of accumulating snowfall, In summer dreams...',
            backgroundColor: "#BFBFBF",
        },
        {
            key: 15,
            anum: "149",
            acronymn: "BZ",
            kind: 'Snow Weather ❄️',
            title: 'Blizzard',
            desc: 'Strong winter storm with subfreezing temps and very strong winds, low visiblity.',
            backgroundColor: "#BFBFBF",
        },
        {
            key: 16,
            anum: "150",
            acronymn: "SF",
            kind: 'Snow Weather ❄️',
            title: 'Snow Flurry',
            desc: 'Quick snowfall of variable intensity, typically resulting in little accumulation.',
            backgroundColor: "#BFBFBF",
        },
        {
            key: 17,
            anum: "151",
            acronymn: "SQU",
            kind: 'Snow Weather ❄️',
            title: 'Snow Squall',
            desc: 'Short duration but intense snow event with high wind and low visiblity.',
            backgroundColor: "#BFBFBF",
        },
]