export default snowWeather = [ 
        {
            key: 0,
            anum: "134",
            acronymn: "CN",
            kind: 'Snow Formations ❄️',
            title: 'Cornice',
            desc: 'Overhanging build-up	of snow, sometimes looking like a wave, hanging over a ridge.',
            backgroundColor: "#ddefb7",
        },
        {
            key: 1,
            anum: "135",
            acronymn: "AVA",
            kind: 'Snow Formations ❄️',
            title: 'Avalanche',
            desc: 'A rapid slide of snow down a hillside or mountain; Snow flow dangerous and deadly.',
            backgroundColor: "#ddefb7",
        },
        {
            key: 2,
            anum: "136",
            acronymn: "SB",
            kind: 'Snow Formations ❄️',
            title: 'Snow Bridge',
            desc: 'A span of snow arcing over a void, such as a crevasse or gap, but destined to collapse.',
            backgroundColor: "#ddefb7",
        },
        {
            key: 3,
            anum: "137",
            acronymn: "DR",
            kind: 'Snow Formations ❄️',
            title: 'Snowdrift',
            desc: 'Wind and snowfall combine in an artful manner to form a wide variety of snow shapes.',
            backgroundColor: "#ddefb7",
        },
        {
            key: 4,
            anum: "138",
            acronymn: "FD",
            kind: 'Snow Formations ❄️',
            title: 'Finger Drift',
            desc: 'A narrow drift of snow, up to 36 inches wide; Several close by resemble a hand.',
            backgroundColor: "#ddefb7",
        },
        {
            key: 5,
            anum: "139",
            acronymn: "PD",
            kind: 'Snow Formations ❄️',
            title: 'Pillow Drift',
            desc: 'A drift of snow often 10-15 feet long and 1-3 feet wide; No idea why its called "pillow".',
            backgroundColor: "#ddefb7",
        },

]