export default snowWeather = [ 
        {
            key: 0,
            anum: "134",
            acronymn: "CN",
            kind: 'Snow Formations ❄️',
            title: 'Cornice',
            desc: 'Overhanging build-up	of snow, sometimes looking like a wave, hanging over a ridge.',
            backgroundColor: "#DDEBF7",
        },
        {
            key: 1,
            anum: "135",
            acronymn: "AVA",
            kind: 'Snow Formations ❄️',
            title: 'Avalanche',
            desc: 'A rapid slide of snow down a hillside or mountain; Snow flow dangerous and deadly.',
            backgroundColor: "#DDEBF7",
        },
        {
            key: 2,
            anum: "136",
            acronymn: "SB",
            kind: 'Snow Formations ❄️',
            title: 'Snow Bridge',
            desc: 'A span of snow arcing over a void, such as a crevasse or gap, but destined to collapse.',
            backgroundColor: "#DDEBF7",
        },
        {
            key: 3,
            anum: "137",
            acronymn: "DR",
            kind: 'Snow Formations ❄️',
            title: 'Snowdrift',
            desc: 'Wind and snowfall combine in an artful manner to form a wide variety of snow shapes.',
            backgroundColor: "#DDEBF7",
        },
        {
            key: 4,
            anum: "138",
            acronymn: "FD",
            kind: 'Snow Formations ❄️',
            title: 'Finger Drift',
            desc: 'A narrow drift of snow, up to 36 inches wide; Several close by resemble a hand.',
            backgroundColor: "#DDEBF7",
        },
        {
            key: 5,
            anum: "139",
            acronymn: "PD",
            kind: 'Snow Formations ❄️',
            title: 'Pillow Drift',
            desc: 'A drift of snow often 10-15 feet long and 1-3 feet wide; No idea why its called "pillow".',
            backgroundColor: "#DDEBF7",
        },
        {
            key: 6,
            anum: "140",
            acronymn: "RP",
            kind: 'Snow Formations ❄️',
            title: 'Ripple Marks',
            desc: 'Corrugated surface of snow created by wind; Looks like the ripples on a sandy surface.',
            backgroundColor: "#DDEBF7",
        },
        {
            key: 7,
            anum: "141",
            acronymn: "CAV",
            kind: 'Snow Formations ❄️',
            title: 'Snow Cave',
            desc: 'A shelter carved into snow bank by animals or people to protect from wind and cold.',
            backgroundColor: "#DDEBF7",
        },
        {
            key: 8,
            anum: "142",
            acronymn: "KIK",
            kind: 'Snow Formations ❄️',
            title: 'Kicker',
            desc: 'A curved ramp that sends the rider up into the air, for launcing big air, tricks, big falls.',
            backgroundColor: "#DDEBF7",
        },
        {
            key: 9,
            anum: "143",
            acronymn: "PIP",
            kind: 'Snow Formations ❄️',
            title: 'Half Pipe',
            desc: 'A terrain feature shaped like a half tube of snow, with a down-hill pitch, for tricks.',
            backgroundColor: "#DDEBF7",
        },
        {
            key: 10,
            anum: "144",
            acronymn: "MOG",
            kind: 'Snow Formations ❄️',
            title: 'Mogul',
            desc: 'Series of snow bumps formed by skiers who push snow into oval-rounded shapes.',
            backgroundColor: "#DDEBF7",
        },
        {
            key: 11,
            anum: "145",
            acronymn: "PIL",
            kind: 'Snow Formations ❄️',
            title: 'Pillow',
            desc: 'A soft pile of snow atop a rock or raised feature; Really fun to drop onto from above.',
            backgroundColor: "#DDEBF7",
        },
        {
            key: 12,
            anum: "146",
            acronymn: "MAN",
            kind: 'Snow Formations ❄️',
            title: 'Snowman',
            desc: 'Stacked structure of 3 snowballs, w/ smaller ones on top, highest ball with face features.',
            backgroundColor: "#DDEBF7",
        },
        {
            key: 13,
            anum: "147",
            acronymn: "WOM",
            kind: 'Snow Formations ❄️',
            title: 'Snowwoman',
            desc: 'Much like Snowman, but containing artful and gender-specific features and fashions.',
            backgroundColor: "#DDEBF7",
        },
        {
            key: 14,
            anum: "148",
            acronymn: "SS",
            kind: 'Snow Weather ❄️',
            title: 'Snowstorm',
            desc: 'Winter storm with some amounts of accumulating snowfall, In summer dreams...',
            backgroundColor: "#BFBFBF",
        },
        {
            key: 15,
            anum: "149",
            acronymn: "BZ",
            kind: 'Snow Weather ❄️',
            title: 'Blizzard',
            desc: 'Strong winter storm with subfreezing temps and very strong winds, low visiblity.',
            backgroundColor: "#BFBFBF",
        },
        {
            key: 16,
            anum: "150",
            acronymn: "SF",
            kind: 'Snow Weather ❄️',
            title: 'Snow Flurry',
            desc: 'Quick snowfall of variable intensity, typically resulting in little accumulation.',
            backgroundColor: "#BFBFBF",
        },
        {
            key: 17,
            anum: "151",
            acronymn: "SQU",
            kind: 'Snow Weather ❄️',
            title: 'Snow Squall',
            desc: 'Short duration but intense snow event with high wind and low visiblity.',
            backgroundColor: "#BFBFBF",
        },
        {
            key: 18,
            anum: "152",
            acronymn: "BUR",
            kind: 'Snow Weather ❄️',
            title: 'Snowburst',
            desc: "Intense but quick snowfall resulting in fast accumulation; And it's fun to say!",
            backgroundColor: "#BFBFBF",
        },
        {
            key: 19,
            anum: "153",
            acronymn: "BLO",
            kind: 'Snow Weather ❄️',
            title: 'Blowing Snow',
            desc: 'Wind-carried snow sometimes reaching great heights, visibility bad at ground level.',
            backgroundColor: "#BFBFBF",
        },
        {
            key: 20,
            anum: "154",
            acronymn: "DS",
            kind: 'Snow Weather ❄️',
            title: 'Drifting Snow',
            desc: 'Wind-driven snow at ground level, in some areas at depths that exceed average amount.',
            backgroundColor: "#BFBFBF",
        },
        {
            key: 21,
            anum: "155",
            acronymn: "SE",
            kind: 'Snow Weather ❄️',
            title: 'Seasonal Snow',
            desc: 'Snow accumulating over the course of one season, then melts at the end of the season.',
            backgroundColor: "#BFBFBF",
        },
        {
            key: 22,
            anum: "156",
            acronymn: "PS",
            kind: 'Snow Weather ❄️',
            title: 'Perennial Snow',
            desc: 'Accumulated snow that lasts more than one ski season into the next year.',
            backgroundColor: "#BFBFBF",
        },
        {
            key: 23,
            anum: "157",
            acronymn: "DU",
            kind: 'Snow Weather ❄️',
            title: 'Dumping',
            desc: 'Generically heavy snowfall accumulating rapidly (see PU, NU).',
            backgroundColor: "#BFBFBF",
        },
        {
            key: 24,
            anum: "158",
            acronymn: "PU",
            kind: 'Snow Weather ❄️',
            title: 'Puking',
            desc: 'Generic very heavy snowfall accumulating rapidly (see DU, NU).',
            backgroundColor: "#BFBFBF",
        },
        {
            key: 25,
            anum: "159",
            acronymn: "NU",
            kind: 'Snow Weather ❄️',
            title: 'Nuking',
            desc: 'Generic extra heavy snowfall accumulating rapidly (see DU, PU).',
            backgroundColor: "#BFBFBF",
        },
        {
            key: 26,
            anum: "160",
            acronymn: "NAD",
            kind: 'Snow Weather ❄️',
            title: 'Snow-nadow',
            desc: 'Wind-whipped snow spinning like a tornado but not storm-related.',
            backgroundColor: "#BFBFBF",
        },
        {
            key: 27,
            anum: "161",
            acronymn: "NO",
            kind: 'Snow Weather ❄️',
            title: "Nor'easter",
            desc: 'Strong winter storm that pounds northeast coast of America with big snow, rain, waves.',
            backgroundColor: "#BFBFBF",
        },
        {
            key: 28,
            anum: "162",
            acronymn: "WO",
            kind: 'Snow Weather ❄️',
            title: 'Whiteout',
            desc: 'Condition where it is hard to find a horizon due to snow surface, clouds, snowfall, wind.',
            backgroundColor: "#BFBFBF",
        },
        {
            key: 29,
            anum: "163",
            acronymn: "BCY",
            kind: 'Snow Weather ❄️',
            title: 'Bomb Cyclone',
            desc: 'Strong winter storm distinguished by low pressure, large size, and quick formation.',
            backgroundColor: "#BFBFBF",
        },
        {
            key: 30,
            anum: "164",
            acronymn: "TS",
            kind: 'Snow Weather ❄️',
            title: 'Thunder Snow',
            desc: 'A snow storm that has lightning and thunder; Rare but very cool, just ask Jim Cantore.',
            backgroundColor: "#BFBFBF",
        },
        {
            key: 31,
            anum: "165",
            acronymn: "SMG",
            kind: 'Snow Weather ❄️',
            title: 'Snowmageddon',
            desc: '(also Snowpocalypse and Snowzilla) Media nicknames for big snow storm events.',
            backgroundColor: "#BFBFBF",
        },
        {
            key: 32,
            anum: "166",
            acronymn: "NAM",
            kind: 'Snow Weather ❄️',
            title: '2012',
            desc: 'The Weather Channel started naming winter storms in November 2012; Athena was first.',
            backgroundColor: "#BFBFBF",
        },
        {
            key: 33,
            anum: "167",
            acronymn: "LE",
            kind: 'Snow Weather ❄️',
            title: 'Lake Effect',
            desc: 'Big snow producer, when cold dry air passes over open water and dumps over land.',
            backgroundColor: "#BFBFBF",
        },
        {
            key: 34,
            anum: "168",
            acronymn: "PV",
            kind: 'Snow Weather ❄️',
            title: 'Polar Vortex',
            desc: 'Condition where very	cold polar arctic air dips to the south, spawning storms.',
            backgroundColor: "#BFBFBF",
        },
        {
            key: 35,
            anum: '169',
            acronymn: 'WH',
            kind: 'Snow Weather ❄️',
            title: 'Wind Hold',
            desc: 'Temporary stoppage of ski lifts due to high winds; Lifts will normally unload first.',
            backgroundColor: '#BFBFBF',
        },
        {
            key: 36,
            anum: "170",
            acronymn: "KAT",
            kind: 'Snow Weather ❄️',
            title: "Cat's Track",
            desc: 'In Maine, just enough new snow on the ground to track a cat.',
            backgroundColor: "#BFBFBF",
        },
        {
            key: 37,
            anum: "171",
            acronymn: "CM",
            kind: 'Snow Oddities ❄️',
            title: "Chionomania",
            desc: 'Abnormal fear of, or	a dislike of, snow; (Is that a real thing?).',
            backgroundColor: "#BDD7EE",
        },
        {
            key: 38,
            anum: "172",
            acronymn: "SHK",
            kind: 'Snow Oddities ❄️',
            title: "Snowhawk",
            desc: "Narrow strip of snow left behind on roof of vehicle (can't reach) after brushing-off rest.",
            backgroundColor: "#BDD7EE",
        },
        {
            key: 39,
            anum: "173",
            acronymn: "FB",
            kind: 'Snow Oddities ❄️',
            title: "Fenderberg (aka, Car Poop)",
            desc: "Dark, ugly build-up of hard frozen snow behind tires of vehicle.",
            backgroundColor: "#BDD7EE",
        },
        {
            key: 40,
            anum: "174",
            acronymn: "GU",
            kind: 'Snow Oddities ❄️',
            title: "Guinness World Record",
            desc: 'Largest snowflake 15" diameter, 1887 near Miles City, Montana.',
            backgroundColor: "#BDD7EE",
        },
        {
            key: 41,
            anum: "175",
            acronymn: "FLA",
            kind: 'Snow Oddities ❄️',
            title: "Flake",
            desc: 'Slang for snow in general, such as "I shredded some flake".',
            backgroundColor: "#BDD7EE",
        },
        {
            key: 42,
            anum: "176",
            acronymn: "BLI",
            kind: 'Snow Oddities ❄️',
            title: "Snow Blindness",
            desc: 'Eye condition caused by UV rays from sun, poor eye protection; Painful but avoidable.',
            backgroundColor: "#BDD7EE",
        },
        {
            key: 43,
            anum: "177",
            acronymn: "SKL",
            kind: 'Snow Oddities ❄️',
            title: "Snorkel Snow",
            desc: 'Snow so deep that a snorkel is needed to breathe while skiing; Legend from Alta, UT.',
            backgroundColor: "#BDD7EE",
        },
        {
            key: 44,
            anum: "178",
            acronymn: "SIT",
            kind: 'Snow Oddities ❄️',
            title: "Sitzmark",
            desc: 'A depression in the snow surface left by a fallen skier, most especially backwards.',
            backgroundColor: "#BDD7EE",
        },
        {
            key: 45,
            anum: "179",
            acronymn: "WOR",
            kind: 'Snow Oddities ❄️',
            title: "300",
            desc: '"Sami" languages of Norway, Sweden and Finland have up to 300 words for snow.',
            backgroundColor: "#BDD7EE",
        },
        {
            key: 46,
            anum: "180",
            acronymn: "JOR",
            kind: 'Snow Oddities ❄️',
            title: "Skijoring",
            desc: 'Speed and skill competition where horse-drawn skiers race on snowy streets.',
            backgroundColor: "#BDD7EE",
        },
        {
            key: 47,
            anum: "181",
            acronymn: "KIT",
            kind: 'Snow Oddities ❄️',
            title: "Kite Skiing",
            desc: 'Activity using wind and kite to propel skier/boarder across snow, like kiteboarder.',
            backgroundColor: "#BDD7EE",
        },
        {
            key: 48,
            anum: "182",
            acronymn: "BOB",
            kind: 'Snow Oddities ❄️',
            title: "Skibobbing",
            desc: 'Activity using bicycle fitted with skiis to enable steerable rides/descents on snow.',
            backgroundColor: "#BDD7EE",
        },
        {
            key: 49,
            anum: "183",
            acronymn: "SaM",
            kind: 'Snow Oddities ❄️',
            title: "Snow a Mineral",
            desc: 'Technically speaking, snow could be defined as a mineral: natural, inorganic, 1 substance.',
            backgroundColor: "#BDD7EE",
        },
        {
            key: 50,
            anum: "184",
            acronymn: "SPE",
            kind: 'Snow Oddities ❄️',
            title: "Snow Speed",
            desc: 'Snowflakes usually float as they fall from sky; But they can fall at rates up to 9MPH.',
            backgroundColor: "#BDD7EE",
        },
        {
            key: 51,
            anum: "185",
            acronymn: "SiH",
            kind: 'Snow Oddities ❄️',
            title: "Snowball in Hell",
            desc: 'Death Valley, California, one of hottest places in the world, had snow in December 2008.',
            backgroundColor: "#BDD7EE",
        },
        {
            key: 52,
            anum: "186",
            acronymn: "OS",
            kind: 'Snow Oddities ❄️',
            title: "Snowball in Hell",
            desc: 'In 1992, Syracuse, NY City Counsel outlawed snow after a really bad	winter. Really bad!',
            backgroundColor: "#BDD7EE",
        },
        {
            key: 53,
            anum: "187",
            acronymn: "CIT",
            kind: 'Snow Oddities ❄️',
            title: "Snow City",
            desc: 'Snowiest city in the	world is Aomori, Japan with an average of 312" per year.',
            backgroundColor: "#BDD7EE",
        },
        {
            key: 54,
            anum: "188",
            acronymn: "GLO",
            kind: 'Snow Oddities ❄️',
            title: "Alpenglow",
            desc: 'Reddish or pink glow appearing on high mountain peaks at dawn or early morning.',
            backgroundColor: "#BDD7EE",
        },
        {
            key: 55,
            anum: "189",
            acronymn: "COL",
            kind: 'Snow Oddities ❄️',
            title: "Snow Color",
            desc: 'Actually, snow is translucent, but as light passes through, it appears white/blue ** can also be "stained" pink, red, yellow and brown, too.',
            backgroundColor: "#BDD7EE",
        },
        {
            key: 56,
            anum: "190",
            acronymn: "ROO",
            kind: 'Snow Oddities ❄️',
            title: "Roostertail",
            desc: 'A spray of snow emanating from back of snowboard or ski & shooting up in the air.',
            backgroundColor: "#BDD7EE",
        },
        {
            key: 57,
            anum: "191",
            acronymn: "SFL",
            kind: 'Snow Oddities ❄️',
            title: "Snowflake",
            desc: 'Derogatory slang for a person with an exaggerated sense of uniqueness/entitlement.',
            backgroundColor: "#BDD7EE",
        },
        {
            key: 58,
            anum: "192",
            acronymn: "CAT",
            kind: 'Snow Oddities ❄️',
            title: "Snowcat",
            desc: 'Snow grooming machines made by: Bombardier, PistenBully, Prinoth, Tucker, Thiokol.',
            backgroundColor: "#BDD7EE",
        },
        {
            key: 59,
            anum: "193",
            acronymn: "PPsd",
            kind: 'International Snow Classification for Seasonal Snow (Grain Shape) ❄️',
            title: "Precipitation Particles",
            desc: '(PPsd) Six-sided star-like stellars or dendrites.',
            backgroundColor: "#B3F7F5",
        },
        {
            key: 60,
            anum: "194",
            acronymn: "MMrp",
            kind: 'International Snow Classification for Seasonal Snow (Grain Shape) ❄️',
            title: "Machine-Made Snow",
            desc: '(MMrp) Round polycrystalline particle, w/protrusions.',
            backgroundColor: "#B3F7F5",
        },










        {
            key: 71,
            anum: "205",
            acronymn: "PPpl",
            kind: 'Snow Flake Types Precipitation Particles (Subclasses) ❄️',
            title: "Plates",
            desc: '(PPpl) Plate-like, mostly hexagonal shape.',
            backgroundColor: "#ACE7FD",
        },
]